Easybeefstew
szabowexler/cookbook pull request #36
Opened 2016-11-20 21:46 UTC by dfryer1193

Nomnomnom

2016-11-21 14:46 UTC, szabowexler commented on recipes/Beef/EasyBeefStew.recipe
> +  - Cut beef into 1.5 inch cubes, toss with flour.
Huh - out of curiosity, what's the effect of searing, then dredging, then braising? I've seen some that call for dredging before the searing (e.g. http://www.reluctantgourmet.com/flouring-meat/), but I don't really feel like I know what the big difference is. Perhaps the science of cooking or the food lab has the answer...?

2016-11-21 14:46 UTC, szabowexler requested changes
Could you also add the updated cookbook.pdf, just so we always have all recipes present there, so we can share the link out? :)

2016-11-21 14:48 UTC, szabowexler commented
Also, you might be interested in http://cooking.nytimes.com/recipes/1016029-wine-braised-oxtail -- I made it last night, and it was pretty good. We're going to try adapting the recipe for beef chuck instead of oxtail (the oxtail was a bit too fatty), but overall it was pretty amazing.

2016-11-21 14:53 UTC, dfryer1193 commented
I'll update the PDF when I get home!

The effect of partially searing is to let the beef keep a touch more moisture during the braising process. It's the same technique found in (this Food Lab article)[http://www.seriouseats.com/2016/01/food-lab-follow-the-rules-for-the-best-all-american-beef-stew.html]. Curiously, I was doing this before reading that article.

The dredging is effectively optional, you'll just end up with a slightly thinner stew than if you added no flour. It helps to prevent clumping in the flour, compared to simply adding the flour on its own.

2016-11-23 22:40 UTC, dfryer1193 commented
Updated pdf!

2016-11-23 23:45 UTC, szabowexler commented
oof -- looks like you're going to have to merge in master, and then re-add the PDF. State changes mean you're in a bad state here.

2016-11-24 00:18 UTC, dfryer1193 commented
*sigh* let's try this again.

2016-11-27 16:28 UTC, szabowexler approved these changes

2016-11-27 16:28 UTC, merged